---
version: 2.1


jobs:

  build-android-arm64:
    docker:
      - image: cimg/android:2023.08-ndk
    environment:
      - OCPN_TARGET: android-aarch64
      - CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - checkout
      - run: ci/circleci-build-android.sh
      - run: ci/maybe-push-upload.sh

  build-android-armhf:
    docker:
      - image: cimg/android:2023.08-ndk
    environment:
      - OCPN_TARGET: android-armhf
      - CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - checkout
      - run: ci/circleci-build-android.sh
      - run: ci/maybe-push-upload.sh

std-filters: &std-filters
  filters:
    branches:
      ignore:
        - tmp
        - /tmp-.*/

workflows:
  version: 2
  build_all:
    jobs:

      - build-android-arm64:
          <<: *std-filters

      - build-android-armhf:
          <<: *std-filters

